name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }} ${{ matrix.tox-env }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: bandit
            python-version: 3.5
            tox-env: py3-bandit
          - name: flake8
            python-version: 3.5
            tox-env: py3-flake8
          - name: Juniper
            python-version: 3.5
            tox-env: py35-django22
          - name: Koa
            python-version: 3.8
            tox-env: py38-django22
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox semantic-version pre-commit
      - name: Display Python version for ${{ matrix.name }}
        run: python -c "import sys; print(sys.version)"
      - name: Test library version
        run: python -c "from tahoe_idp import __version__; from semantic_version import Version; Version(__version__)"
      - name: Test with tox
        run: |
          tox -e ${{ matrix.tox-env }}
